# Generated by Django 2.2 on 2019-12-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btp_land', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='btp_land.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
