# Generated by Django 2.2 on 2019-12-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btp_land', '0008_remove_message_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='linked_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='btp_land.Project'),
            preserve_default=False,
        ),
    ]
